version: '3'

services:
  supermarket-api:
    build: supermarket-api
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://supermarketdb:3306/supermarketdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      supermarketdb:
        condition: service_healthy
  supermarketdb:
    image: mysql:9.5.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: supermarketdb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10